version: '3'

services:
  proselyte-awssqs-demo:
    image: proselyte-awssqs-demo:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EXAMPLE_R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/postgres
      - EXAMPLE_R2DBC_USER=postgres
      - EXAMPLE_R2DBC_PASSWORD=postgres
      - EXAMPLE_DB_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - EXAMPLE_DB_USER=postgres
      - EXAMPLE_DB_PASSWORD=postgres
      - EXAMPLE_AWS_ACCESS_KEY=
      - EXAMPLE_AWS_SECRET_KEY=
      - EXAMPLE_AWS_REGION=us-east-1
      - EXAMPLE_SQS_QUEUE_NAME=awssqsdemo.fifo
      - EXAMPLE_SQS_QUEUE_REGION=us-east-1
    deploy:
      mode: replicated
      replicas: 3