spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    locations: classpath:db/migration
  cloud:
    aws:
      credentials:
        access-key:
        secret-key:
      region:
        static: us-east-1

sqs:
  notification:
    queue:
      name: awssqsdemo.fifo
      region: us-east-1