spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${EXAMPLE_R2DBC_URL}
    username: ${EXAMPLE_R2DBC_USER}
    password: ${EXAMPLE_R2DBC_PASSWORD}
  flyway:
    url: ${EXAMPLE_DB_URL}
    user: ${EXAMPLE_DB_USER}
    password: ${EXAMPLE_DB_PASSWORD}
    locations: classpath:db/migration
  cloud:
    aws:
      credentials:
        access-key: ${EXAMPLE_AWS_ACCESS_KEY}
        secret-key: ${EXAMPLE_AWS_SECRET_KEY}
      region:
        static: ${EXAMPLE_AWS_REGION}

sqs:
  notifications:
    queue:
      name: ${EXAMPLE_SQS_QUEUE_NAME}
      region: ${EXAMPLE_SQS_QUEUE_NAME}